# Generated by Django 5.0.1 on 2024-02-06 09:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.TextField(blank=True)),
                ('client_picture', models.TextField(blank=True)),
                ('number_of_stars', models.FloatField(default=0.0)),
                ('feedback', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='project_pictures')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.TextField(blank=True)),
                ('project_description', ckeditor.fields.RichTextField(blank=True)),
                ('live_link', models.TextField(blank=True)),
                ('project_pictures', models.ManyToManyField(blank=True, to='mainapp.picture')),
            ],
        ),
    ]
